name: Auto Format for Creator Frontend

on:
  pull_request:
    branchs-ignore:
    - 'main'
    paths:
    - 'frontend/test-app/**'

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Formatting
      run: |
        npm install
        npm run format
      working-directory: ./frontend/test-app
    - name: Commit
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Auto commit code format"
        git push origin ${{ github.head_ref }}
      working-directory: ./
